### ISSUE TITLE
Unable to get diagnostics, get battery voltage etc..

### ISSUE THREAD

**Issue by garytaylor** [barnybug/ener314#1]
Hi @barnybug  - sorry to have to ask for help !  Im using your code to try and talk to my energenie mihome devices.  Specifically, I want the diagnostics information as well as setting the valve state and other useful things.

I used your code from the cmd/main.go and whenever I received the temperature from a device, I tried to send it a command - according to the logs the command was sent but I am getting nothing back from the devices whether I ask for diagnostics, voltage or anything.

Its been a while since I first set up the raspberry pi with the energenie pi mote 2 way board - as well as installing your code - so I honestly cannot remember how I set it up.

Can you think of a reason why my devices would not respond ?  I promise to leave you alone after this !!  I might have some contributions such as enabling the use of a thermostat etc.. at some point - I will do a PR for this.

**Comment by barnybug** [comment]
Hi,

It's not obvious why this wouldn't work for you - I'd check the transmission is successful, range, etc. From what I recall it should light red when transmitting, so try watching the board alongside log output to see if this happens following the receive.

**Comment by barnybug** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by garytaylor** [comment]
Hi 
Sorry,I have been away and not able to spend any time on this.

I am back on it now - this is what I have discovered.

1. The LED does come on when data is sent
2. I can see the data being sent and can see that something comes back straight away (I have attached part of the log)
3. I can see no battery voltage or diagnostics information coming back which I am requesting by uncommenting your comments (see my code which comes from the main.go in cmd/ener314)

I would also like to point out that my hub is still running, which will also be talking to the radiator valves - I only thought of this last night - do you think I need to turn this off whilst I am messing around ?

Thanks

Gary

**Comment by barnybug** [comment]
Yes definitely, the hub may be talking over these.
